install.packages("tidyverse")
library(tidyverse)
googleplaystore <- read_csv("googleplaystore.csv")
install.packages("corrplot")
library(corrplot)
View(cor_mat)
plot(applystore$Installs, applystore$Reviews)
library("scales")
options(scipen=10000)
simple.regression <- lm(Installs ~ Reviews, data = applystore)
summary(simple.regression)
multiple.regression <- lm(Installs ~ Reviews + Rating, data = applystore)
summary(multiple.regression)
library(tidyverse)
#data cleanup

applystore |> ggplot(aes(x = Reviews, y= Installs))
applystore |> ggplot(aes(x = Reviews, y= Installs)) +geom_point() +geom_smooth(method = 'lm') + expand_limits(x = c(0, NA), y = c(0, NA)) +
  scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6))
library("caret")
library(descale)
library(dplyr)
library(scales)
library(ggplot2)
ggplot(applystore, aes(x= Installs, y= Reviews, col = category)) +
geom_point() + xlim(1,5) + geom_smooth(method = "lm")
library(ggplot2)
glimpse(applystore)
applystore$Category <- as.factor(applystore$Category)
